# e-frontier EF-GP2
# https://activesupport.co.jp/free/ef-gp2
axis_linear: 3  # Forward/Back
scale_linear: 0.2
scale_linear_turbo: 0.8

axis_angular: 0  # Left/Right
scale_angular: 0.5

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
